### PR TITLE
Small Bugfix

### PR DESCRIPTION
**Pull request by myw**
Hope you guys don't mind: I noticed a few imports were missing from the code plotting example, so I filled them in.

Sorry about the sloppiness of the commit. There seems to be something funny going on with terminal newlines, and I tried to fix it, but that just led to a bit more sloppiness.

Great course so far!

### CODE REVIEW

**Comment by marcua** [comment]
Awesome thanks!  We'll look through this soon and apply it to our copy!

**Comment by marcua** [comment]
Couldn't help peaking at it: this includes a bunch of stuff you checked into your own repo (day2/work, etc.)

Sorry to bother you, but do you mind submitting a pull request with only the fixes?  Thanks!

**Comment by myw** [comment]
Sorry! I thought I had fixed that. Let me try to resubmit.

**Comment by myw** [comment]
I realize why this happened: first pull request guys, sorry. It's because I made the pull request from my master branch, and not from a specific branch. I'm closing this request now and will submit a different, cleaner request in a sec from an appropriate branch.

**Pull request closed without merging**
